accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from . import views


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.profile, name='view_profile_with_primary_key'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset,
        {
            'template_name': 'accounts/reset_password.html',
            'post_reset_redirect': 'accounts:password_reset_done',
            'email_template_name': 'accounts/reset_password_email.html'
        }, name='password_reset'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {
            'template_name': 'accounts/reset_password_confirm.html',
            'post_reset_redirect': 'accounts:password_reset_complete'
        }, name='password_reset_confirm'),

    url(r'^password-reset/complete/$', password_reset_complete,
        {
            'template_name': 'accounts/reset_password_complete.html'
        }, name='password_reset_complete')
]

django_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django_project import views

urlpatterns = [
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from home.views import HomeView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends,
        name='change_friends'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=20, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_user_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required= True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )
        exclude = ()

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:register')
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


def profile(request, pk=None):

    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
    <title>Password settings</title>
{% endblock %}

{% block body %}
    <div class="container">
    <h1>Profile</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">SAVE</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
    <title>Edit profile</title>
{% endblock %}

{% block body %}
    <div class="container">
    <h1>Profile</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">SAVE</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<h1>Welcome !</h1>
    <p>You can log-in here...</p>
    <h3>LOGIN!</h3>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">LOGIN</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<h1>Logged Out</h1>
    <p>
        You have been logged out !
    </p>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block head %} 
    {% if user.first_name %}
        {% with a as b %}
            <title>{{ user.first_name }}'s profile</title>
        {% endwith %}
    {% else %}
        <title>{{ user.username }}'s profile</title>

    {% endif %}

{% endblock %}

{% block body %}
    <div class="container jumbotron">
        <h1>{{ user.username }}'s<span style="font-size: medium"> Profile</span></h1>

        <p>Description : {{ user.userprofile.description }}</p>
    <br><br>
    <p>NAME         :   {{ user.first_name }} {{ user.last_name }}</p>
    <p>EMAIL        :   {{ user.email }}</p>
    <p>PHONE NUMBER :   {{ user.userprofile.phone }}</p>
        {% if user.userprofile.image %}
            {% with a as b %}
                <img src="{{ user.userprofile.image.url }}" width="240">
            {% endwith %}
        {% else %}
            <h6>(No image uploaded ) </h6>
        {% endif %}

    </div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
    <h1>Register</h1>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
    <button class="btn btn-primary" type="submit">REGISTER</button>
</form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<h1>Reset Password</h1>
    <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}<br>
    <button type="submit" class="btn btn-success">Send Reset Link!</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <br>
        <h2>Password reset Complete...</h2>

    <a href="{% url 'accounts:login' %}">Log Back In !</a>

    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<h1>Link Verified !</h1>
        <br>
        <h2>Enter New Password...</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}<br>
    <button type="submit" class="btn btn-success">Reset Password</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
<h1>Reset Password Sent </h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered.
        You should receive them shortly.
        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>

    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

	{% trans "Thanks for using our site!" %}

	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

	{% endautoescape %}