accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
from . import views


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.profile, name='view_profile_with_primary_key'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset,
        {
            'template_name': 'accounts/reset_password.html',
            'post_reset_redirect': 'accounts:password_reset_done',
            'email_template_name': 'accounts/reset_password_email.html'
        }, name='password_reset'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {
            'template_name': 'accounts/reset_password_confirm.html',
            'post_reset_redirect': 'accounts:password_reset_complete'
        }, name='password_reset_confirm'),

    url(r'^password-reset/complete/$', password_reset_complete,
        {
            'template_name': 'accounts/reset_password_complete.html'
        }, name='password_reset_complete')
]

django_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django_project import views

urlpatterns = [
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from home.views import HomeView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends,
        name='change_friends'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=20, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_user_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required= True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )
        exclude = ()

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:register')
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


def profile(request, pk=None):

    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form':form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '../static/sttyle.css' %}?v=22" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>Login@Socio</title>
    {% endblock %}
</head>
<body>

   <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home:home' %}">Social Network</a>
    </div>
    {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home:home' %}" >Home</a></li>
        <li><a href="{% url 'accounts:profile' %}" >Profile</a></li>
        <li><a href="{% url 'accounts:edit_profile' %}" >Edit Profile</a></li>
        <li><a href="{% url 'accounts:change_password' %}" >Change Password</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-user"></span> Log Out</a></li>

    </ul>
      {% else %}
        <ul class="nav navbar-nav">
        <li>
            <a href="{% url 'accounts:password_reset' %}">Reset Password</a>
        </li>
        </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:login' %}" >Log in</a></li>
        <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>

    </ul>
      {% endif %}
  </div>
</nav>

<br><br>
{% block body %}
    <h1>Base</h1>
{% endblock %}
</body>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">

</script>
</html>